#### NumPy arrays, operations, broadcasting, and Pandas ,DataFrames, Series, indexing, and data grouping.

In [1096]:
import numpy as np;
import pandas as pd;

marks = np.array([65, 72, 88, 91, 56, 79, 84, 95, 68, 73])
print(marks)

[65 72 88 91 56 79 84 95 68 73]

In [1097]:
import numpy as np                  

arr = np.array([10, 20, 30, 40, 50])
print(arr[2])          #Indexing
print(arr[1:4])        #Slicing

30
[20 30 40]

In [1098]:
arr = np.array([10, 20, 30, 40])     #Array operation
print(arr*2)

[20 40 60 80]

In [1099]:
arr = np.array([10,20,30,40,50])  #Basic statistics
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())

150
30.0
50
10

In [1100]:
arr = np.array([      #Row,cols
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.shape)

(2, 3)

In [1101]:
arr = np.array([10, 20, 30])  #Broadcasting

print(arr + 5)

[15 25 35]

In [1102]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[1,1])

50

### Pandas

In [1103]:
df = pd.DataFrame([11,12,13],columns=["Random_No"])
df

   Random_No
0         11
1         12
2         13

In [1104]:
data = {
    "Name": ["Riya","Shayam","Siya","Naina"],
    "Age" : [16,23,24,21],
    "Carrer" : ["Studies","Job","Learning","College"]
}

In [1105]:
df = pd.DataFrame(data)

In [1106]:
df.head()

     Name  Age    Carrer
0    Riya   16   Studies
1  Shayam   23       Job
2    Siya   24  Learning
3   Naina   21   College

In [1107]:
df.rename(columns={'Carrer':'Career_Path'},inplace=True)

In [1108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         4 non-null      object
 1   Age          4 non-null      int64
 2   Career_Path  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes

In [1109]:
df.to_csv('Test_Data.csv',index=False)

In [1110]:
df = pd.read_csv(r'..\Month_1\Test_Data.csv')
df

     Name  Age Career_Path
0    Riya   16     Studies
1  Shayam   23         Job
2    Siya   24    Learning
3   Naina   21     College

In [1111]:
#Row & column selection 
df[['Name','Age']] #Colummn Selected

     Name  Age
0    Riya   16
1  Shayam   23
2    Siya   24
3   Naina   21

In [1112]:
# Selecting Rows
# Loc - Label based index
# df.loc[df.Name =='Riya']
df.loc[0:2]
# df.loc[(df.Name =='Riya') & (df.Age > 15)]

     Name  Age Career_Path
0    Riya   16     Studies
1  Shayam   23         Job
2    Siya   24    Learning

In [1113]:
#df.iloc[0]
df.iloc[0:2] #start,end-1     Index

     Name  Age Career_Path
0    Riya   16     Studies
1  Shayam   23         Job

In [1114]:
#Filtering
age_filter = df[df['Age'] > 18]
age_filter

     Name  Age Career_Path
1  Shayam   23         Job
2    Siya   24    Learning
3   Naina   21     College

In [1115]:
df.where(df['Age']>18)  #Condition Filtering

     Name   Age Career_Path
0     NaN   NaN         NaN
1  Shayam  23.0         Job
2    Siya  24.0    Learning
3   Naina  21.0     College

### Rows and columns - Operations(Add,Update,Delete)

In [1116]:
df

     Name  Age Career_Path
0    Riya   16     Studies
1  Shayam   23         Job
2    Siya   24    Learning
3   Naina   21     College

In [1117]:
df['Salary'] = [20000,15000,25000,5000]
df

     Name  Age Career_Path  Salary
0    Riya   16     Studies   20000
1  Shayam   23         Job   15000
2    Siya   24    Learning   25000
3   Naina   21     College    5000

In [1118]:
df['Bonus'] = df['Salary'] * 0.2
df

     Name  Age Career_Path  Salary   Bonus
0    Riya   16     Studies   20000  4000.0
1  Shayam   23         Job   15000  3000.0
2    Siya   24    Learning   25000  5000.0
3   Naina   21     College    5000  1000.0

In [1119]:
df.loc[len(df)] = ['Rohan',17,'HR',30000,3000]

In [1120]:
len(df)

5

In [1121]:
#Updating value - using index value
df.loc[0,'Salary'] = 15000
df

     Name  Age Career_Path  Salary   Bonus
0    Riya   16     Studies   15000  4000.0
1  Shayam   23         Job   15000  3000.0
2    Siya   24    Learning   25000  5000.0
3   Naina   21     College    5000  1000.0
4   Rohan   17          HR   30000  3000.0

In [1122]:
# updating value -using column value
df.loc[df.Name == 'Rohan','Age'] = 20
df

     Name  Age Career_Path  Salary   Bonus
0    Riya   16     Studies   15000  4000.0
1  Shayam   23         Job   15000  3000.0
2    Siya   24    Learning   25000  5000.0
3   Naina   21     College    5000  1000.0
4   Rohan   20          HR   30000  3000.0

In [980]:
#Delete value - row and column value
df = df.drop(df[df['Name'] == 'Naina'].index) # Drop row , axis =0

In [1062]:
#df.drop(1,axis=0)

In [1123]:
df.drop('Bonus',axis=1,inplace=True)

In [1124]:
#df.drop(['Bonus','Salary'],axis=1)

In [1125]:
df

     Name  Age Career_Path  Salary
0    Riya   16     Studies   15000
1  Shayam   23         Job   15000
2    Siya   24    Learning   25000
3   Naina   21     College    5000
4   Rohan   20          HR   30000

In [1126]:
#Sort values
df.sort_values('Salary',ascending=False)

     Name  Age Career_Path  Salary
4   Rohan   20          HR   30000
2    Siya   24    Learning   25000
0    Riya   16     Studies   15000
1  Shayam   23         Job   15000
3   Naina   21     College    5000

### Working with date Values

In [1127]:
df['Date'] = ['2025-02-04','2026-04-04','2025-04-14','2025-10-05','2026-10-15']
df

     Name  Age Career_Path  Salary        Date
0    Riya   16     Studies   15000  2025-02-04
1  Shayam   23         Job   15000  2026-04-04
2    Siya   24    Learning   25000  2025-04-14
3   Naina   21     College    5000  2025-10-05
4   Rohan   20          HR   30000  2026-10-15

In [1128]:
df['Date'].dtypes

dtype('O')

In [1129]:
df.rename(columns={'Date':'DOJ'},inplace=True)
df

     Name  Age Career_Path  Salary         DOJ
0    Riya   16     Studies   15000  2025-02-04
1  Shayam   23         Job   15000  2026-04-04
2    Siya   24    Learning   25000  2025-04-14
3   Naina   21     College    5000  2025-10-05
4   Rohan   20          HR   30000  2026-10-15

In [1130]:
df['DOJ'].dtypes

dtype('O')

In [1131]:
df.loc[len(df)] = 'Rishaab',23,'CA',50000,'2026-08-09'

In [1132]:
df['DOJ'] = pd.to_datetime(df['DOJ'])
df['DOJ'].dtypes

dtype('<M8[ns]')

In [1133]:
df['DOJ1'] = ['04-02-2026','17-06-2025','04-10-2025','02-08-2026','02-09-2025','22-12-2026']
df

      Name  Age Career_Path  Salary        DOJ        DOJ1
0     Riya   16     Studies   15000 2025-02-04  04-02-2026
1   Shayam   23         Job   15000 2026-04-04  17-06-2025
2     Siya   24    Learning   25000 2025-04-14  04-10-2025
3    Naina   21     College    5000 2025-10-05  02-08-2026
4    Rohan   20          HR   30000 2026-10-15  02-09-2025
5  Rishaab   23          CA   50000 2026-08-09  22-12-2026

In [1134]:
df['DOJ1'] = pd.to_datetime(df['DOJ1'],format='%d-%m-%Y')
df['DOJ1']

0   2026-02-04
1   2025-06-17
2   2025-10-04
3   2026-08-02
4   2025-09-02
5   2026-12-22
Name: DOJ1, dtype: datetime64[ns]

In [1135]:
df.drop('DOJ1',axis=1,inplace=True)

In [1136]:
df

      Name  Age Career_Path  Salary        DOJ
0     Riya   16     Studies   15000 2025-02-04
1   Shayam   23         Job   15000 2026-04-04
2     Siya   24    Learning   25000 2025-04-14
3    Naina   21     College    5000 2025-10-05
4    Rohan   20          HR   30000 2026-10-15
5  Rishaab   23          CA   50000 2026-08-09

In [1137]:
df['Month'] = df['DOJ'].dt.month
df['Year'] = df['DOJ'].dt.year
df['Week_Day'] = df['DOJ'].dt.day_name()
df

      Name  Age Career_Path  Salary        DOJ  Month  Year  Week_Day
0     Riya   16     Studies   15000 2025-02-04      2  2025   Tuesday
1   Shayam   23         Job   15000 2026-04-04      4  2026  Saturday
2     Siya   24    Learning   25000 2025-04-14      4  2025    Monday
3    Naina   21     College    5000 2025-10-05     10  2025    Sunday
4    Rohan   20          HR   30000 2026-10-15     10  2026  Thursday
5  Rishaab   23          CA   50000 2026-08-09      8  2026    Sunday

In [1138]:
df['Probation_Period'] = df['DOJ'] + pd.Timedelta(days=90)
df

,Name,Age,Career_Path,Salary,DOJ,Month,Year,Week_Day,Probation_Period
0,Riya,16,Studies,15000,2025-02-04,2,2025,Tuesday,2025-05-05
1,Shayam,23,Job,15000,2026-04-04,4,2026,Saturday,2026-07-03
2,Siya,24,Learning,25000,2025-04-14,4,2025,Monday,2025-07-13
3,Naina,21,College,5000,2025-10-05,10,2025,Sunday,2026-01-03
4,Rohan,20,HR,30000,2026-10-15,10,2026,Thursday,2027-01-13
5,Rishaab,23,CA,50000,2026-08-09,8,2026,Sunday,2026-11-07

In [1139]:
#Handling missing values
df.isnull()

,Name,Age,Career_Path,Salary,DOJ,Month,Year,Week_Day,Probation_Period
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False

In [1140]:
import numpy as np

In [1141]:
df.loc[df.Name== 'Rohan','Salary'] = np.nan

In [1142]:
df

,Name,Age,Career_Path,Salary,DOJ,Month,Year,Week_Day,Probation_Period
0,Riya,16,Studies,15000.0,2025-02-04,2,2025,Tuesday,2025-05-05
1,Shayam,23,Job,15000.0,2026-04-04,4,2026,Saturday,2026-07-03
2,Siya,24,Learning,25000.0,2025-04-14,4,2025,Monday,2025-07-13
3,Naina,21,College,5000.0,2025-10-05,10,2025,Sunday,2026-01-03
4,Rohan,20,HR,NaN,2026-10-15,10,2026,Thursday,2027-01-13
5,Rishaab,23,CA,50000.0,2026-08-09,8,2026,Sunday,2026-11-07

In [1143]:
df.isnull().sum()

Name                0
Age                 0
Career_Path         0
Salary              1
DOJ                 0
Month               0
Year                0
Week_Day            0
Probation_Period    0
dtype: int64

In [1144]:
df.fillna(0)

,Name,Age,Career_Path,Salary,DOJ,Month,Year,Week_Day,Probation_Period
0,Riya,16,Studies,15000.0,2025-02-04,2,2025,Tuesday,2025-05-05
1,Shayam,23,Job,15000.0,2026-04-04,4,2026,Saturday,2026-07-03
2,Siya,24,Learning,25000.0,2025-04-14,4,2025,Monday,2025-07-13
3,Naina,21,College,5000.0,2025-10-05,10,2025,Sunday,2026-01-03
4,Rohan,20,HR,0.0,2026-10-15,10,2026,Thursday,2027-01-13
5,Rishaab,23,CA,50000.0,2026-08-09,8,2026,Sunday,2026-11-07

### Aggregation and Group by

In [1145]:
df['Month'].value_counts()

Month
4     2
10    2
2     1
8     1
Name: count, dtype: int64

In [1149]:
df[df['Month']==4].value_counts()

Name    Age  Career_Path  Salary   DOJ         Month  Year  Week_Day  Probation_Period
Shayam  23   Job          15000.0  2026-04-04  4      2026  Saturday  2026-07-03          1
Siya    24   Learning     25000.0  2025-04-14  4      2025  Monday    2025-07-13          1
Name: count, dtype: int64

In [1155]:
#Group By
df.groupby('Month')['Salary'].sum()

Month
2     15000.0
4     40000.0
8     50000.0
10     5000.0
Name: Salary, dtype: float64

In [1157]:
df.groupby('Month')['Salary'].mean()

Month
2     15000.0
4     20000.0
8     50000.0
10     5000.0
Name: Salary, dtype: float64

In [1159]:
df.groupby('Month').agg({'Salary':'mean','Name':'count'})

        Salary  Name
Month
2      15000.0     1
4      20000.0     2
8      50000.0     1
10      5000.0     2

### Concatenate and Merge Dataframes(Joins)

In [1166]:
df1 = pd.DataFrame({'ID':[1,2,3,4],'Name':['Shreya','Suman','Anu','Kopal']})
df1

   ID    Name
0   1  Shreya
1   2   Suman
2   3     Anu
3   4   Kopal

In [1163]:
df2 = pd.DataFrame({'ID':[1,2,3,4,5],'Scores':[45,34,54,65,76]})
df2

   ID  Scores
0   1      45
1   2      34
2   3      54
3   4      65
4   5      76

In [1167]:
pd.concat([df1,df2],axis=0)

   ID    Name  Scores
0   1  Shreya     NaN
1   2   Suman     NaN
2   3     Anu     NaN
3   4   Kopal     NaN
0   1     NaN    45.0
1   2     NaN    34.0
2   3     NaN    54.0
3   4     NaN    65.0
4   5     NaN    76.0

In [ ]:
pd.concat([df1,df2],axis=1) #horizontal/Column-wise

    ID    Name  ID  Scores
0  1.0  Shreya   1      45
1  2.0   Suman   2      34
2  3.0     Anu   3      54
3  4.0   Kopal   4      65
4  NaN     NaN   5      76

In [1173]:
pd.merge(df1,df2,how='inner', on='ID')

   ID    Name  Scores
0   1  Shreya      45
1   2   Suman      34
2   3     Anu      54
3   4   Kopal      65

In [1174]:
pd.merge(df1,df2,how='inner', left_on='ID',right_on='ID')

   ID    Name  Scores
0   1  Shreya      45
1   2   Suman      34
2   3     Anu      54
3   4   Kopal      65

#### Creating Dataframe to practice pivot table in pandas